version: '3'

services:
  mysql:
    image: mysql:5.7.30
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "mycrm"
      MYSQL_USER: "default"
      MYSQL_PASSWORD: "secret"
    volumes:
      - mysqldata:/var/lib/mysql

  dev:
    build: 
      context: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ../debug/:/var/debug
    working_dir: /var/www

  prod:
    image: kagawish/shrtr:latest
    ports:
      - "80:80"
    working_dir: /var/www

volumes:
  mysqldata:
    driver: "local"